version: "3"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: web
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_HOST: 172.17.0.1
  writer:
    image: writer:latest
    command: python main.py
    ports:
      - 8080:8080
  reader:
    image: reader:latest
    command: python main.py
    ports:
      - 8081:8081
volumes:
  db_data: {}
